#!/bin/bash -ex

source ./environment

MIPMAP=1

cleanup() {
    docker stop mysql
    docker rm -fv mysql
}

trap "cleanup" INT TERM EXIT

docker run --name mysql \
    -e MYSQL_DATABASE=poeatlas \
    -e MYSQL_ALLOW_EMPTY_PASSWORD=yes \
    -e MYSQL_USER=poeatlas \
    -e MYSQL_PASSWORD=poeatlas\
    -d mysql/mysql-server

while docker ps | grep mysql | grep -qv healthy; do
    # after 10 minutes, fails
    sleep 1
done

JAVA_OPTS="-Dspring.datasource.url=\"jdbc:mysql://mysql:3306/poeatlas?useSSL=false\""
JAVA_OPTS="$JAVA_OPTS -Dspring.datasource.username=\"poeatlas\""
JAVA_OPTS="$JAVA_OPTS -Dspring.datasource.password=\"poeatlas\""

#get Content.ggpk data
git clone https://github.com/poeatlas/Content.ggpk.git

#create new atlas.json file from dats
docker run --rm --name cli --link mysql:mysql \
    -e JAVA_OPTS="$JAVA_OPTS" \
    -v $PWD/Content.ggpk:/usr/src/app \
    poeatlas/cli:${CLI_VERSION} \
    dat -input /usr/src/app/Data/ -output /usr/src/app/output/atlas.json

#find all dds files for extraction
cd Content.ggpk
DDS_FILES=$(find . -name '*.dds')

#convert dds files to png
docker run --rm --name cli --link mysql:mysql \
    -e JAVA_OPTS="$JAVA_OPTS" \
    -v $PWD:/usr/src/app \
    -P \
    poeatlas/cli:${CLI_VERSION} \
    dds -mipmap ${MIPMAP} -root /usr/src/app/ ${DDS_FILES}

# get out of Content.ggpk dir
cd ..

#copy new atlas.json into atlas-ui submodule and build atlas-ui
git clone https://github.com/poeatlas/atlas-ui.git
cp -Rf ./Content.ggpk/output/atlas.json ./atlas-ui/src/resources/atlas.json
cd atlas-ui
npm install
npm run build
cd ..

TMP_DIR=$(mktemp -d)

#push Art to poeatlas site project
#git clone https://${GH_TOKEN}@github.com/poeatlas/poeatlas.github.io.git
#git stash -u

git remote set-url origin https://${GH_TOKEN}@github.com/poeatlas/poeatlas.github.io.git
git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
git pull origin master

#git fetch origin master
#cp  -R ./atlas-ui/build/* .
mv ./Content.ggpk/Art ${TMP_DIR}
mv ./atlas-ui/build/* ${TMP_DIR}
#mv ./index.html .${TMP_DIR}
#mv ./static .${TMP_DIR}
#mv ./favicon.ico .${TMP_DIR}

git checkout master

if [ -d ./Art ];
then
  git rm -rf ./Art
fi

if [ -f ./index.html ];
then
  git rm -rf ./index.html
fi

if [ -d ./static ];
then
  git rm -rf ./static
fi

if [ -f ./favicon.ico ];
then
  git rm -rf ./favicon.ico
fi

if [ -f ./style.css ];
then
  git rm -rf ./style.css
fi

if [ -f ./service-worker.js ];
then
  git rm -rf ./service-worker.js
fi

mv ${TMP_DIR}/* $PWD
find ./Art -name '*.dds' -exec rm -rf {} \;
#git add ./Art/ ./index.html ./static ./favicon.ico ./style.css ./service-worker.js

rm -rf atlas-ui/
rm -rf Content.ggpk/

git add .
git commit . -m "[skip ci] Updated atlas.json and art files."
git push

#    -it \
# bash

#docker run --rm --name cli --net="host" poeatlas/cli dat
