#!/bin/bash -ex

prepareFiles() {
    #copy new atlas.json into atlas-ui submodule and build atlas-ui
    git clone https://github.com/poeatlas/atlas-ui.git
    cd atlas-ui
    npm install
    npm run build
    cd ..

    git remote set-url origin https://${GH_TOKEN}@github.com/poeatlas/poeatlas.github.io.git
    git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
    git pull origin master

    git checkout master
}