#!/bin/bash -ex

pushFiles() {
    rm -rf ./${POE_VERSION}
    mkdir -p ./${POE_VERSION}
    cp -rf ./${TMP_DIR}/* ./${POE_VERSION}
    cp -f ./${POE_VERSION}/index.html ./
    find ./${POE_VERSION}/Art -name '*.dds' -exec rm -rf {} \;
    #git add ./Art/ ./index.html ./static ./favicon.ico ./style.css ./service-worker.js

    git add ./$POE_VERSION $PWD/index.html

    # remove these files from add list
    git reset atlas-ui/
    git reset Content.ggpk/

    git commit -m "[skip ci] Updated atlas.json and art files."
    git push
}