#!/bin/bash -ex

pushFiles() {
    rm -rf ./${POE_VERSION}
    mkdir -p ./${POE_VERSION}

    cp -rf ./atlas-ui/build/* ./${POE_VERSION}
    cp -f ./${POE_VERSION}/index.html ./

    git add ./$POE_VERSION ./index.html

    # remove these files from add list
    git reset atlas-ui/

    git commit -m "[skip ci] Deploying POE_VERSION=${POE_VERSION}, ATLAS_UI_VERSION=${ATLAS_UI_VERSION}."
    git push
}